// @generated by tools/sync-version.mjs from version.json. Do not edit.
//
// REQ-REPO-187: the product version and the internal schema versions have one
// source of truth. Run `pnpm version:sync` after changing version.json.

/**
 * The AudioGubbins product release version, as users see it. This is the only
 * version a user is ever shown; the schema versions below are internal
 * compatibility identifiers and must not be presented as a product version.
 */
export const PRODUCT_VERSION = '0.1.0' as const;

/**
 * Versions of the persisted formats this build reads and writes. Each moves
 * independently of the product version and of every other entry.
 */
export const SCHEMA_VERSIONS = {
  userPreferences: 1,
  workspaceLayout: 1,
  shortcutProfile: 1,
  logVerbosity: 1,
  keyboardLayout: 1,
  diagnosticBundle: 1,
} as const satisfies Record<string, number>;

/** Name of a persisted format with an independent compatibility version. */
export type SchemaName = keyof typeof SCHEMA_VERSIONS;
