// @generated by tools/sync-version.mjs from version.json. Do not edit.
//
// REQ-REPO-187: the product version and the internal schema versions have one
// source of truth. Run `pnpm version:sync` after changing version.json.

/// Major component of the AudioGubbins product release version.
pub const PRODUCT_VERSION_MAJOR: u32 = 0;

/// Minor component of the AudioGubbins product release version.
pub const PRODUCT_VERSION_MINOR: u32 = 1;

/// Patch component of the AudioGubbins product release version.
pub const PRODUCT_VERSION_PATCH: u32 = 0;

/// The AudioGubbins product release version, as users see it.
pub const PRODUCT_VERSION: &str = "0.1.0";

/// Version of the persisted `userPreferences` schema.
pub const USER_PREFERENCES_SCHEMA_VERSION: u32 = 1;

/// Version of the persisted `workspaceLayout` schema.
pub const WORKSPACE_LAYOUT_SCHEMA_VERSION: u32 = 1;

/// Version of the persisted `shortcutProfile` schema.
pub const SHORTCUT_PROFILE_SCHEMA_VERSION: u32 = 1;

/// Version of the persisted `logVerbosity` schema.
pub const LOG_VERBOSITY_SCHEMA_VERSION: u32 = 1;

/// Version of the persisted `keyboardLayout` schema.
pub const KEYBOARD_LAYOUT_SCHEMA_VERSION: u32 = 1;

/// Version of the persisted `diagnosticBundle` schema.
pub const DIAGNOSTIC_BUNDLE_SCHEMA_VERSION: u32 = 1;
