#!/usr/bin/env node
/**
 * Propagates the AudioGubbins version identifiers from `version.json` into
 * every manifest and generated constants file that has to agree with them.
 *
 * REQ-REPO-187 requires one primary product release version shared across the
 * web application and the first-party Godot integration packages, and requires
 * that the independent internal compatibility identifiers (project schema,
 * persistence schema, and so on) are never conflated with it. Keeping those
 * numbers in one file and generating the rest is what makes that checkable.
 *
 * Usage:
 *   node tools/sync-version.mjs            rewrite every target to match
 *   node tools/sync-version.mjs --check    exit non-zero if any target is stale
 *
 * The `--check` form is the generated-file freshness gate that REQ-REPO-188.1
 * places in the fast commit tier.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative, resolve } from 'node:path';
import { globSync } from 'node:fs';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK_ONLY = process.argv.includes('--check');

const SEMVER = /^(\d+)\.(\d+)\.(\d+)$/;

/** Reads and validates `version.json`, the single source of truth. */
function readVersionManifest() {
  const path = join(REPO_ROOT, 'version.json');
  const manifest = JSON.parse(readFileSync(path, 'utf8'));

  if (typeof manifest.product !== 'string' || !SEMVER.test(manifest.product)) {
    throw new Error(
      `version.json: "product" must be a three-part version, got ${manifest.product}`,
    );
  }
  if (typeof manifest.schemas !== 'object' || manifest.schemas === null) {
    throw new Error('version.json: "schemas" must be an object of schema name to integer version');
  }
  for (const [name, value] of Object.entries(manifest.schemas)) {
    if (!Number.isInteger(value) || value < 1) {
      throw new Error(`version.json: schema "${name}" must be a positive integer, got ${value}`);
    }
  }
  return manifest;
}

/** Converts `userPreferences` to `USER_PREFERENCES` for Rust constant naming. */
function screamingSnakeCase(camel) {
  return camel.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase();
}

/** Renders the generated Rust constants for the audiogubbins-version crate. */
function renderRustConstants(manifest) {
  const [major, minor, patch] = manifest.product.split('.');
  const schemaConstants = Object.entries(manifest.schemas)
    .map(
      ([name, value]) =>
        `/// Version of the persisted \`${name}\` schema.\n` +
        `pub const ${screamingSnakeCase(name)}_SCHEMA_VERSION: u32 = ${value};`,
    )
    .join('\n\n');

  return `// @generated by tools/sync-version.mjs from version.json. Do not edit.
//
// REQ-REPO-187: the product version and the internal schema versions have one
// source of truth. Run \`pnpm version:sync\` after changing version.json.

/// Major component of the AudioGubbins product release version.
pub const PRODUCT_VERSION_MAJOR: u32 = ${major};

/// Minor component of the AudioGubbins product release version.
pub const PRODUCT_VERSION_MINOR: u32 = ${minor};

/// Patch component of the AudioGubbins product release version.
pub const PRODUCT_VERSION_PATCH: u32 = ${patch};

/// The AudioGubbins product release version, as users see it.
pub const PRODUCT_VERSION: &str = "${manifest.product}";

${schemaConstants}
`;
}

/**
 * Renders the TypeScript version package, which is the whole of its source.
 *
 * Its own package rather than a module inside another, for the reason the Rust
 * crate is its own crate: every package that stores something needs to say
 * which format it wrote, and a version registry kept inside the logging package
 * would make each of them depend on logging to find out.
 */
function renderTypeScriptConstants(manifest) {
  const schemaEntries = Object.entries(manifest.schemas)
    .map(([name, value]) => `  ${name}: ${value},`)
    .join('\n');

  return `// @generated by tools/sync-version.mjs from version.json. Do not edit.
//
// REQ-REPO-187: the product version and the internal schema versions have one
// source of truth. Run \`pnpm version:sync\` after changing version.json.

/**
 * The AudioGubbins product release version, as users see it. This is the only
 * version a user is ever shown; the schema versions below are internal
 * compatibility identifiers and must not be presented as a product version.
 */
export const PRODUCT_VERSION = '${manifest.product}' as const;

/**
 * Versions of the persisted formats this build reads and writes. Each moves
 * independently of the product version and of every other entry.
 */
export const SCHEMA_VERSIONS = {
${schemaEntries}
} as const satisfies Record<string, number>;

/** Name of a persisted format with an independent compatibility version. */
export type SchemaName = keyof typeof SCHEMA_VERSIONS;
`;
}

/** Every file that must agree with version.json, and how to bring it into line. */
function buildTargets(manifest) {
  const targets = [];

  const packageJsonPaths = [
    join(REPO_ROOT, 'package.json'),
    ...globSync('apps/*/package.json', { cwd: REPO_ROOT }).map((p) => join(REPO_ROOT, p)),
    ...globSync('packages/*/package.json', { cwd: REPO_ROOT }).map((p) => join(REPO_ROOT, p)),
  ];

  for (const path of packageJsonPaths) {
    targets.push({
      path,
      render: () => {
        const source = readFileSync(path, 'utf8');
        const parsed = JSON.parse(source);
        if (parsed.version === manifest.product) return source;
        // Rewrite only the version field so formatting and key order survive.
        const replaced = source.replace(/("version"\s*:\s*)"[^"]*"/, `$1"${manifest.product}"`);
        if (!/"version"\s*:/.test(source)) {
          throw new Error(`${relative(REPO_ROOT, path)} has no "version" field to synchronise`);
        }
        return replaced;
      },
    });
  }

  targets.push({
    path: join(REPO_ROOT, 'Cargo.toml'),
    render: () => {
      const source = readFileSync(join(REPO_ROOT, 'Cargo.toml'), 'utf8');
      return source.replace(
        /(\[workspace\.package\][\s\S]*?\nversion\s*=\s*)"[^"]*"/,
        `$1"${manifest.product}"`,
      );
    },
  });

  targets.push({
    path: join(REPO_ROOT, 'crates/audiogubbins-version/src/generated.rs'),
    render: () => renderRustConstants(manifest),
  });

  targets.push({
    path: join(REPO_ROOT, 'packages/version/src/index.ts'),
    render: () => renderTypeScriptConstants(manifest),
  });

  return targets;
}

function main() {
  const manifest = readVersionManifest();
  const targets = buildTargets(manifest);
  const stale = [];

  for (const target of targets) {
    const desired = target.render();
    let current = null;
    try {
      current = readFileSync(target.path, 'utf8');
    } catch (error) {
      if (error.code !== 'ENOENT') throw error;
    }

    if (current === desired) continue;

    stale.push(relative(REPO_ROOT, target.path).replaceAll('\\', '/'));
    if (!CHECK_ONLY) {
      writeFileSync(target.path, desired, 'utf8');
    }
  }

  if (stale.length === 0) {
    console.log(`AudioGubbins ${manifest.product}: every version target is current.`);
    return;
  }

  if (CHECK_ONLY) {
    console.error(
      `AudioGubbins ${manifest.product}: ${stale.length} version target(s) are stale.\n` +
        stale.map((p) => `  - ${p}`).join('\n') +
        '\n\nRun `pnpm version:sync` and commit the result.',
    );
    process.exitCode = 1;
    return;
  }

  console.log(
    `AudioGubbins ${manifest.product}: updated ${stale.length} target(s).\n` +
      stale.map((p) => `  - ${p}`).join('\n'),
  );
}

main();
